### ISSUE TITLE
dataset issue

### ISSUE THREAD

**Issue by 980202006** [krystalan/MMCR#3]
Some lyrics include an interlude in the beginning and ending time. Such as:
![image](https://user-images.githubusercontent.com/24452502/147658413-cd8cba9d-5fec-42f2-ab4d-c834344b046c.png)

**Comment by krystalan** [comment]
Yep, It is actually a flaw in this work. Because the time span of each lyric is automatically extracted from each corresponding `.lrc` file .

In `.lrc` file, each lyric is annotated with the beginning time, we automatically use the beginning time of the next lyric as the ending time of the current lyric.

**Comment by 980202006** [comment]
Thank you!
